version: '3.9'


services:
  backend:
    build: ./petsgram-be
    restart: always
    ports:
      - 5001:5000
    env_file:
      - .env
    volumes:
      - ./petsgram-be/uploads:/app/uploads
    depends_on:
      - db
    command: ["flask", "run"]
  frontend:
    build: ./petsgram-fe
    restart: always
    ports:
      - 5002:5000
    env_file:
      - .env
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - petsdb:/var/lib/postgresql
volumes:
  petsdb:

